### ISSUE TITLE
Issue with Rapid's setPower(): cannot change power level

### ISSUE THREAD

**Issue by nzjankovic** [nicolasmcnair/magpy#11]
Hello there,

First off, big fan of you guys and this entire project! Everything has been working pretty well so far, but I've hit a roadblock: I cannot change the intensity level of the stimulator using the `Rapid` class' `setPower()` method. I've tried different values, putting it into enhanced power mode, setting `receipt` & `delay` to True and to False, checking the source code for insight, but I can't figure it out. Any guidance would be greatly appreciated!

Here are the default parameters before `setPower()` is called, and the error message to the `setPower()` call:

> (0, {'instr': {'standby': 1, 'armed': 0, 'ready': 0, 'coilPresent': 1, 'replaceCoil': 0, 'errorPresent': 0, 'errorType': 0, 'remoteStatus': 1}, 'rapid': {'enhancedPowerMode': 0, 'train': 0, 'wait': 0, 'singlePulseMode': 1, 'hvpsuConnected': 1, 'coilReady': 1, 'thetaPSUDetected': 0, 'modifiedCoilAlgorithm': 0}, 'rapidParam': {'power': 30, 'frequency': 0.0, 'nPulses': 0, 'duration': 0.0, 'wait': 0.1}})

> Traceback (most recent call last):
>   File "C:\...\serialport_test_magpy.py", line 16, in <module>
>     myMagstim.setPower(newPower=40, receipt=False, delay=True)
>   File "C:\...\anaconda3\envs\psychopy\lib\site-packages\magpy\magstim.py", line 1231, in setPower
>     if self.isEnhanced():
>   File "C:\...\anaconda3\envs\psychopy\lib\site-packages\magpy\magstim.py", line 1065, in isEnhanced
>     return bool(parameters['rapid']['enhancedPowerMode']) if not error else False
> KeyError: 'rapid'

**Comment by nzjankovic** [comment]
I should also note I'm using a Rapid2 purchased circa 2010, with software version 8.0.

**Comment by nzjankovic** [comment]
I believe I've narrowed down the problem, although I am not sure what the fix is. On line 1060 of `magstim.py` is where the `Rapid` class' `IsEnhanced()` method starts, and this seems to be where the issue is for me.

>      def isEnhanced(self):
>         """ 
>         Helper function that returns True if the Rapid is in enhanced power mode, False if not if it could not be determined.
>         """
>         error,parameters = self._queryCommand()
>         return bool(parameters['rapid']['enhancedPowerMode']) if not error else False

Now, `self._queryCommand()` calls `getSystemStatus()`, which, for someone like me using an old version (8.0) of the Magstim software, returns a `Magstim.SYSTEM_STATUS_VERSION_ERR` of this: `(15, 'SYSTEM_STATUS_VERSION_ERR: Method getSystemStatus() is not compatible with your software version.')`.  

So, what the issue appears to be is that `parameters` contains the string `'SYSTEM_STATUS_VERSION_ERR: Method getSystemStatus() is not compatible with your software version.'`. Then, when `parameters` is passed to the `bool()` function, it breaks because it's not a dict, and does not contain `'rapid'` nor `'enhancedPowerMode'` - it looks like `parameters` should instead contain the dict provided by the `getParameters()` function.

**Comment by nzjankovic** [comment]
So I've managed to write a (quick and dirty) patch that seems to work (note: this is only for the `Rapid` class' `isEnhanced()` method; I don't know if the same solution will work if similar problems arise with the other stimulator classes ... and perhaps I'm the only one these days who is using the old Magstim software (v 8.0)):

```
    def isEnhanced(self):
        """ 
        Helper function that returns True if the Rapid is in enhanced power mode, False if not if it could not be determined.
        """
        error,parameters = self._queryCommand()
        err,currParams = self.getParameters()  ##NZJ's patch 
        return bool(currParams['rapid']['enhancedPowerMode']) if not error else False  ##NZJ's patch
        #return bool(parameters['rapid']['enhancedPowerMode']) if not error else False
```

You need the `error,parameters = self._queryCommand()`, in there so the `error` integer still gets read by the program. Below that, I added the line `err,currParams = self.getParameters()`. `currParams` will contain the dict with the relevant information for the program to keep going. `currParams`  is passed to `bool()` on the next line, instead of passing `parameters`. I commented out the line that was causing the crash, seen as the last line there.

**Comment by nicolasmcnair** [comment]
Sorry for the late reply. This is weird, since your Rapid shouldn't have an unlock code. Elsewhere in the Magpy the lack of an unlock code should push you onto using the old version of getting the parameters - rather than trying to use getSystemStatus (see lines 868-873 in magstim.py). I will try and find time to take a look at this and see why it didn't do this.
